version: '3.8'

services:
  genie:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:4000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL:-http://localhost}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL:-http://localhost}
      - NEXT_PUBLIC_SERVER_URL=${NEXT_PUBLIC_SERVER_URL:-http://localhost}
      - NEXT_PUBLIC_CLIENT_URL=${NEXT_PUBLIC_CLIENT_URL:-http://localhost}
      - NEXT_DATABASE_URL=${NEXT_DATABASE_URL}
      - NEXT_OPENAI_API_KEY=${NEXT_OPENAI_API_KEY}
      - NEXT_GENIE_MAIL=${NEXT_GENIE_MAIL:-official.genie.ai@gmail.com}
      - NEXT_GENIE_MAIL_PASSWORD=${NEXT_GENIE_MAIL_PASSWORD}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - genie-network

networks:
  genie-network:
    driver: bridge
